package net.dev.permissions.sql;

public enum SQLProperty {

	UUIDCACHE,
	USER_PERMISSIONS,
	USER_PREFIX,
	USER_SUFFIX,
	USER_CHAT_PREFIX,
	USER_CHAT_SUFFIX,
	GROUP_NAMES,
	GROUP_PERMISSIONS,
	GROUP_PARENT,
	GROUP_PREFIX,
	GROUP_SUFFIX,
	GROUP_CHAT_PREFIX,
	GROUP_CHAT_SUFFIX,
	GROUP_MEMBERS,
	GROUP_WEIGHT,
	GROUP_DEFAULT;
	
}
