name: PermissionSystem
version: 4.5
author: Justix
main: net.dev.permissions.PermissionSystem
soft-depend: [EazyNick, Clans, ClansAPI, PlaceholderAPI]

commands:
  perms:
    aliases:
    - perm
    - permission
  rank:
  debugperms: