name: PermissionSystem
version: 4.9
author: Justix
main: net.dev.permissions.PermissionSystem
softdepend: [EazyNick, Clans, ClansAPI, PlaceholderAPI, Vault]
api-version: 1.13

commands:
  perms:
    aliases:
    - perm
    - permission
  rank:
  debugperms: